version: '3.9'
services:
  website_screenshot_api:
    build: .
    container_name: website_screenshot-website_screenshot_api-1
    restart: unless-stopped
    ports:
      - "127.0.0.1:3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
